Settings.general = {
     colorscheme = 'towervim',
  -- colorscheme = 'tokyonight-storm',
  -- colorscheme = 'tokyonight-moon',
  -- colorscheme = 'darkplus',
  -- colorscheme = 'onedarker-italic',
  -- colorscheme = 'onedarker',
 -- colorscheme = 'horizon',
  -- colorscheme = 'synthwave84',
  -- colorscheme = 'darktower',
  formatOnSave = false,
  trimWhitespace = false,
  lineDiagnostics = true
}

Settings.gui = {
  kind = {
    Class = ' ',
    Color = ' ',
    Constant = 'ﲀ ',
    Constructor = ' ',
    Enum = '練',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = '',
    Folder = ' ',
    Function = ' ',
    Interface = 'ﰮ ',
    Keyword = ' ',
    Method = ' ',
    Module = ' ',
    Operator = '',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    Struct = ' ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = '塞',
    Value = ' ',
    Variable = ' ',
  },
  diagnostics = {
    error = '',
    warning = '',
    hint = '',
    info = '',
  },
}
